version: '3.8'

services:
  laravel:
    container_name: laravel
    image: yang/laravel9
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=postgresql
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - postgresql
    restart: always

  postgresql:
    container_name: postgresql
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=yang
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_DATABASE=laravel
    volumes:
      - postgresql_data:/bitnami/postgresql
    restart: always

  php:
    container_name: php
    image: php:8.1.3-fpm
    working_dir: /var/www
    volumes:
      - ./app/:/var/www/
    
  nginx:
    container_name: nginx
    image: nginx:1.21.6
    working_dir: /var/www
    ports:
      - '80:80'
    volumes:
      - ./app/:/var/www/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: always
  

volumes:
  postgresql_data:
    driver: local
